### ISSUE TITLE
help + licence

### ISSUE THREAD

**Issue by fabsenet** [BrianLima/HueHue#1]
Hi!

I noticed, you are using some of my code from [adrilight](https://github.com/fabsenet/adrilight).

I only want to let you know, that you have to follow the licence of the code.

[MIT Licence](https://github.com/fabsenet/adrilight/blob/master/LICENSE):

>...
>The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
>...

If you could add a proper notice, this would be good.

Apart from that, if you need any help, we could talk about your project and I noticed, you are using WPF. I wanted to port adrilight to WPF as well, we could join forces here... just let me know!

**Comment by BrianLima** [comment]
Hi @fabsenet , sorry for that, i'm just on early works on my project and hadn't put atention to the license nor the README yet, i'm really sorry.

I'm aiming to control the LED kit i built with an arduino to light my PC case and found your code really useful, specially about talking to the arduino to send the colors that each LED should be, if you could explain to me a little better how you do it, it would help me immensely!

I like to work with WPF, i have some experience in my day to day job and i have a small work that i built that demonstrates some of the UI design i could do to help you at https://github.com/BrianLima/UWPHook.

Do you have a contribution guide for Adrilight? What are you aiming for your UI?
