### ISSUE TITLE
[Desktop App] App don't start

### ISSUE THREAD

**Issue by hitech95** [BrianLima/HueHue#9]
Hi,
looks like that the app on Windows10 x64 don't run.

Do you have any idea on how I could debug it?

**Comment by BrianLima** [comment]
Does it throw an error or something?

**Comment by hitech95** [comment]
Nop, just open than close. I tried to open in terminal but without success.

Right now microsoft website is kinda "down" so I cant download VisualStudio to try to build from sources...
I have VS15 and can't download all the needed libs... (No idea why) I'm new with C# and .NET

C and Java guy here :)

**Comment by BrianLima** [comment]
It didn't start a single time? 

Have you added RGB.NET to the nugget sources?

Could you go into "%AppData%\Roaming\Briano" and "%appdata%\Local\Briano" and delete the files on these directories?

**Comment by hitech95** [comment]
Nop, never started.

> Have you added RGB.NET to the nugget sources?

Uhm how? I just downloded the EXE on your release/tag page.
If you mean to build from sources I cant build I have a pretty old version of F# on my machine setup only to build C/C++ and F#. And microsoft server looks "down" (web page are not rendered correctly, alements are missing etc) from Italy.

If you can explain to me how to install all the additional packages via nugget ... right now I get only errors when I try...

**Comment by BrianLima** [comment]
I talk, in order to build it, you would need VS 2017, at least 2015 with the C# part installed, and configure RGB.NET and MyGet as package sources, since VisualStudio.com is down, you will not be able to do it.

I'm trying to debug it on a new system my self to see if i can find the cause of the crash you are facing. i'll report back soon or tomorrow.

Also, check on Task Manager if there are no HueHue.exe processes, or on the system tray.

**Comment by hitech95** [comment]
No, no processes on the task manager. I tried on 3 different PCs.
Website is back up I'm installing VS 2017. Could link me a guide to how to setup additional libs?
Noob on C# :)

**Comment by BrianLima** [comment]
Just to update, i runned it on a new Windows install and it worked fine, it started minimized and was minimized on the system tray.

You need to add http://lib.arge.be/, more specifically https://www.myget.org/F/rgb_net/api/v3/index.json as a package source on visual studio.

> From the Tools menu, select NuGet Package Manager, Package Manager Settings. Select Package Sources. Then click the plus button to add a new package source. Give it a name and use one of the above feed urls.

Then open the NuGet package manager itself and select the new package source you added. Note that you will need Include prerelease checked to see any NuGet packages for the image processor feed.

**Comment by hitech95** [comment]
Just tried with a new windows instal on a VM and don't work, the folders under %appdata% are not even creted.
I can see the process showing up on task manager but than nothing happends.

**Comment by BrianLima** [comment]
Found the problem, just give me some minutes.

**Comment by hitech95** [comment]
Looks like that when you build the project inside the relase folders there are a lot of dll and libs. On your release only the exe is provided and don't start.

Also check this:
https://github.com/BrianLima/HueHue/blob/f791b9bda7df3e745bbcf9eda604fc18cffc02a3/HueHue/Views/Devices/AddAsusAuraView.xaml.cs#L27

**Comment by BrianLima** [comment]
Please, excuse me for making such a idiot release and not taking care, i'm really sorry for making you lose your time, i uploaded the wrong file indeed.

I also fixed a autostart bug.

The release page is now updated.

**Comment by BrianLima** [comment]
I plan on doing that, right now as i'm doing the very few first releases i'm trying to keep it simple, but it's on the map surely.

**Comment by hitech95** [comment]
If you nead a webiste or hosting space just ask :)
A friend is sending to you a donation for the good work.
(I have done the hardware stuff and the install process for him)

**Comment by BrianLima** [comment]
CAN'T THANK YOU ENOUGH!!!!!!

Right now i'm on vacation and working on a smaller and simpler project, but in the next week i'll come back to working more heavily on HueHue and adding new features and modes to it, glad to hear that it is useful to you 💃

**Comment by Deam96** [comment]
@BrianLima can't thank you enough!!! Your work is amazing, really man, if you are going in this direction i will keep support your work more  !!!

**Comment by BrianLima** [comment]
Feel free to post pictures of your setup to [The subreddit](https://www.reddit.com/r/HueHueApp/) to show people how and what can be done!

Thanks again!
